apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment-v2
  labels:
    app: wisecow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow-app
  template:
    metadata:
      labels:
        app: wisecow-app
    spec:
      containers:
        - name: wisecow-app
          image: naveenm323/wisecow-app:latest
          ports:
            - containerPort: 4499   # 👈 clean int, no hidden characters
