apiVersion: v1
kind: Service
metadata:
  name: wisecow-app
spec:
  type: NodePort
  selector:
    app: wisecow-app
  ports:
  - port: 80        # Cluster internal
    targetPort: 4499  # Container port
    nodePort: 30499   # Fixed NodePort
    protocol: TCP
