apiVersion: v1
kind: Service
metadata:
  name: wisecow-app
spec:
  type: NodePort
  selector:
    app: wisecow-app
  ports:
    - port: 4499        # Service Port
      targetPort: 4499  # Container Port
      nodePort: 30499
