apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 4499        # Cluster internal
      targetPort: 4499  # Container port
      nodePort: 30499   # Fixed NodePort
  type: NodePort
